version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - OPENAI_API_KEY=<your-key-here>
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=vectorbase
    ports:
      - "8000:8000"

  db:
      build:
        context: ./docker-postgres
        dockerfile: postgres.Dockerfile
      volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=vectorbase

volumes:
      postgres_data: 